### ISSUE TITLE
No module named 'PyEMD', after  installing with pip.

### ISSUE THREAD

**Issue by iras** [LRydin/MFDFA#15]
I think this is an issue only present in 0.3.

This can be obviously fixed by pip-installing PyEMD first but it would be nice if the distribution system would take care of it.

**Comment by LRydin** [comment]
Hey @iras. Yup, now I see that also on my side a fresh installation of MFDFA did not include PyEMD :|. I have to fix this.

for now you can just do:
```
pip install EMD-signal
```
and it should solve it :)

**Comment by iras** [comment]
It does. thanks! :)

**Comment by LRydin** [comment]
Wonderful. I'll close this then. I will fix this and make sure the next version of MFDFA includes all dependencies :).
