### ISSUE TITLE
question: About estimation of hurst exponent. 

### ISSUE THREAD

**Issue by yukki-jpn** [LRydin/MFDFA#27]
I have a question about 
1. estimation procedure of the Hurst exponent.

In README.md, you argued ``We will fit the first points, since the results are more accurate there'', and used the first points to estimate Hurst exponent. Is there any evidence, such as papers or results of numerical simulations, that you can say so? (I thought this description was intuitively different from the methods described in the original paper of DFA.)

**Comment by LRydin** [comment]
Dear @yukki-jpn, you caught a very good point – which is in fact incorrect! This is indeed described in the original paper<sup>1</sup>, the authors explicitly state that the optimal lag to fit the fluctuation function is somewhere between `lags > 10` points and `lags < N/4`, with `N` the total number of datapoints.

I am working already on changing this in the README and I have to surely do the same for the documentation, I don't want to lead the reader to something that is incorrect. The results one obtains using short segments are not necessarily wrong, but there are cases where they do lead to wrong estimation. Overall, MFDFA tends to _underestimate_ the Hurst coefficients in purely fractal timeseries.

---

<sup>1</sup>Kantelhardt, J. W., Zschiegner, S. A., Koscielny-Bunde, E., Havlin, S., Bunde, A., & Stanley, H. E. (2002). *Multifractal detrended fluctuation analysis of nonstationary time series*. [Physica A: Statistical Mechanics and Its Applications, 316(1-4), 87–114](https://doi.org/10.1016/S0378-4371(02)01383-3)

**Comment by yukki-jpn** [comment]
Dear @LRydin 
Thank you for your rapid reply. 
``I am working already on changing this in the README and I have to surely do the same for the documentation,''
I am looking forward to that modification.

We are currently writing a paper on the long memory process in the financial market, and we intend to use your program and quote your paper. We, therefore, need some review of our statistical procedure on the estimation of the Hurst exponent. Could you corporate with a review of our paper?

**Comment by yukki-jpn** [comment]
Dear @LRydin 

We are glad to hear such a reply. We want to get in touch with you using email. Could you let me know your email address if you disclose your email address? Otherwise, please send me an email at s2120443(at)s.tsukuba.ac.jp (please replace (at) into @). I think either I or [Dr. Kanazawa](https://scholar.google.com/citations?user=XE2XapQAAAAJ&hl=ja&oi=ao) will make contact with you in a few days.

**Comment by LRydin** [comment]
You can find me at leonardo.rydin@gmail.com :).
